FROM python:3.8-slim

RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsm6 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY app /app

RUN pip install --no-cache-dir flask opencv-python-headless numpy moviepy

EXPOSE 5000

# Запуск веб-сервера
CMD ["python", "main.py"]