FROM python:3.8-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends ffmpeg libsm6 libxext6 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY app /app

RUN mkdir -p /app/uploads /app/processed

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "main:app", "--workers", "4"]
